# Generated by Django 5.0.4 on 2024-04-23 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarDekho_app', '0004_alter_carlist_chassisnumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowroomList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=100)),
                ('website', models.URLField(max_length=100)),
            ],
        ),
    ]
